config/routes.rb
CMTracker::Application.routes.draw do
  get "reports/" => "reports#index"
  get "reports/index"
  get "reports/attendances"
  get "reports/roster"
  get "reports/roster_printout"
  get "reports/checkins"

  devise_for :volunteers
  devise_scope :volunteer do
    match "volunteers/sign_out" => "devise/sessions#destroy"
  end
  get "volunteers" => "volunteers#index"

  # Rails admin
  #mount RailsAdmin::Engine => 'admin', :as => 'rails_admin'

  match "attendances/import" => "attendances#import"
  resources :attendances
  resources :services
  resources :classrooms
  resources :parents
  resources :children

  root :to => "home#index"
  post "processCheckin" => "home#processCheckin"
  post "undoCheckin" => "home#undoCheckin"
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :attendances
  # Not ready to go yet
  # has_many :checked_in_kids, :through => Attendance, :source => :child

  def to_s
    service_date.strftime("%A %I:%M %p -%m/%d/%y")  
  end
  
  def admin_label
    to_s 
  end
end
# == Schema Information
#
# Table name: services
#
#  id           :integer         not null, primary key
#  service_date :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_volunteer!

  # GET /services
  # GET /services.xml
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to(@service, :notice => 'Service was successfully created.') }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(@service, :notice => 'Service was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= form_for @service do |f|
  -if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :service_date
    = f.datetime_select :service_date
  .actions
    = f.submit 'Save'

app/views/services/edit.html.haml
%h1 Editing service

= render 'form'

= link_to 'Show', @service
\|
= link_to 'Back', services_path

app/views/services/index.html.haml
%h1 Listing services

%table
  %tr
    %th Service date
    %th
    %th
    %th

  - @services.each do |service|
    %tr
      %td= service.service_date
      %td= link_to 'Show', service
      %td= link_to 'Edit', edit_service_path(service)
      %td= link_to 'Destroy', service, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Service', new_service_path

app/views/services/new.html.haml
%h1 New service

= render 'form'

= link_to 'Back', services_path

app/views/services/show.html.haml
%p#notice= notice

%p
  %b Service date:
  = @service.service_date

= link_to 'Edit', edit_service_path(@service)
\|
= link_to 'Back', services_path