config/routes.rb
CMTracker::Application.routes.draw do
  get "reports/" => "reports#index"
  get "reports/index"
  get "reports/attendances"
  get "reports/roster"
  get "reports/roster_printout"
  get "reports/checkins"

  devise_for :volunteers
  devise_scope :volunteer do
    match "volunteers/sign_out" => "devise/sessions#destroy"
  end
  get "volunteers" => "volunteers#index"

  # Rails admin
  #mount RailsAdmin::Engine => 'admin', :as => 'rails_admin'

  match "attendances/import" => "attendances#import"
  resources :attendances
  resources :services
  resources :classrooms
  resources :parents
  resources :children

  root :to => "home#index"
  post "processCheckin" => "home#processCheckin"
  post "undoCheckin" => "home#undoCheckin"
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  default_scope :conditions => {:active => true }

  has_many :children
  has_many :volunteers

  def to_s
    self[:name]
  end

  def admin_label
    self[:name]
  end

  def active?
    active
  end
end
# == Schema Information
#
# Table name: classrooms
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  active     :boolean
#

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :authenticate_volunteer!

  # GET /classrooms
  # GET /classrooms.xml
  def index
    @classrooms = Classroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @classrooms }
    end
  end

  # GET /classrooms/1
  # GET /classrooms/1.xml
  def show
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @classroom }
    end
  end

  # GET /classrooms/new
  # GET /classrooms/new.xml
  def new
    @classroom = Classroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @classroom }
    end
  end

  # GET /classrooms/1/edit
  def edit
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.xml
  def create
    @classroom = Classroom.new(params[:classroom])

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to(@classroom, :notice => 'Classroom was successfully created.') }
        format.xml  { render :xml => @classroom, :status => :created, :location => @classroom }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @classroom.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /classrooms/1
  # PUT /classrooms/1.xml
  def update
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      if @classroom.update_attributes(params[:classroom])
        format.html { redirect_to(@classroom, :notice => 'Classroom was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @classroom.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.xml
  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to(classrooms_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.haml
= form_for @classroom do |f|
  -if @classroom.errors.any?
    #error_explanation
      %h2= "#{pluralize(@classroom.errors.count, "error")} prohibited this classroom from being saved:"
      %ul
        - @classroom.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/classrooms/edit.html.haml
%h1 Editing classroom

= render 'form'

= link_to 'Show', @classroom
\|
= link_to 'Back', classrooms_path

app/views/classrooms/index.html.haml
%h1 Listing classrooms

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @classrooms.each do |classroom|
    %tr
      %td= classroom.name
      %td= link_to 'Show', classroom
      %td= link_to 'Edit', edit_classroom_path(classroom)
      %td= link_to 'Destroy', classroom, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Classroom', new_classroom_path

app/views/classrooms/new.html.haml
%h1 New classroom

= render 'form'

= link_to 'Back', classrooms_path

app/views/classrooms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @classroom.name

= link_to 'Edit', edit_classroom_path(@classroom)
\|
= link_to 'Back', classrooms_path