config/routes.rb
CMTracker::Application.routes.draw do
  get "reports/" => "reports#index"
  get "reports/index"
  get "reports/attendances"
  get "reports/roster"
  get "reports/roster_printout"
  get "reports/checkins"

  devise_for :volunteers
  devise_scope :volunteer do
    match "volunteers/sign_out" => "devise/sessions#destroy"
  end
  get "volunteers" => "volunteers#index"

  # Rails admin
  #mount RailsAdmin::Engine => 'admin', :as => 'rails_admin'

  match "attendances/import" => "attendances#import"
  resources :attendances
  resources :services
  resources :classrooms
  resources :parents
  resources :children

  root :to => "home#index"
  post "processCheckin" => "home#processCheckin"
  post "undoCheckin" => "home#undoCheckin"
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  # Properties
  # first_name - String
  # last_name - String
  # email - String
  # phone - String
  # notes - String: Any notes useful to service lead about the family
  # inactive - boolean: Used to mark families that don't attend MHDT anymore
  # onthecity - boolean: Used to mark families that are on The City
  # visitor - boolean: Used to mark families that are one-time visitors
  has_and_belongs_to_many :children

  def to_s
    "#{ first_name } #{ last_name }"
  end

  def admin_label
    to_s
  end
end
# == Schema Information
#
# Table name: parents
#
#  id         :integer         not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  phone      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  notes      :text
#  inactive   :boolean         default(FALSE)
#  onthecity  :boolean
#  visitor    :boolean         default(FALSE)
#

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_filter :authenticate_volunteer!

  # GET /parents
  # GET /parents.xml
  def index
    @parents = Parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parents }
    end
  end

  # GET /parents/1
  # GET /parents/1.xml
  def show
    @parent = Parent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @parent }
    end
  end

  # GET /parents/new
  # GET /parents/new.xml
  def new
    @parent = Parent.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @parent }
    end
  end

  # GET /parents/1/edit
  def edit
    @parent = Parent.find(params[:id])
  end

  # POST /parents
  # POST /parents.xml
  def create
    @parent = Parent.new(params[:parent])

    respond_to do |format|
      if @parent.save
        format.html { redirect_to(@parent, :notice => 'Parent was successfully created.') }
        format.xml  { render :xml => @parent, :status => :created, :location => @parent }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @parent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parents/1
  # PUT /parents/1.xml
  def update
    @parent = Parent.find(params[:id])

    respond_to do |format|
      if @parent.update_attributes(params[:parent])
        format.html { redirect_to(@parent, :notice => 'Parent was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @parent.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.xml
  def destroy
    @parent = Parent.find(params[:id])
    @parent.destroy

    respond_to do |format|
      format.html { redirect_to(parents_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.haml
= form_for @parent do |f|
  -if @parent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@parent.errors.count, "error")} prohibited this parent from being saved:"
      %ul
        - @parent.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/parents/edit.html.haml
%h1 Editing parent

= render 'form'

= link_to 'Show', @parent
\|
= link_to 'Back', parents_path

app/views/parents/index.html.haml
%h1 Listing parents

%table
  %tr
    %th First name
    %th Last name
    %th Email
    %th Phone
    %th
    %th
    %th

  - @parents.each do |parent|
    %tr
      %td= parent.first_name
      %td= parent.last_name
      %td= parent.email
      %td= parent.phone
      %td= link_to 'Show', parent
      %td= link_to 'Edit', edit_parent_path(parent)
      %td= link_to 'Destroy', parent, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Parent', new_parent_path

app/views/parents/new.html.haml
%h1 New parent

= render 'form'

= link_to 'Back', parents_path

app/views/parents/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @parent.first_name
%p
  %b Last name:
  = @parent.last_name
%p
  %b Email:
  = @parent.email
%p
  %b Phone:
  = @parent.phone

= link_to 'Edit', edit_parent_path(@parent)
\|
= link_to 'Back', parents_path