config/routes.rb
CMTracker::Application.routes.draw do
  get "reports/" => "reports#index"
  get "reports/index"
  get "reports/attendances"
  get "reports/roster"
  get "reports/roster_printout"
  get "reports/checkins"

  devise_for :volunteers
  devise_scope :volunteer do
    match "volunteers/sign_out" => "devise/sessions#destroy"
  end
  get "volunteers" => "volunteers#index"

  # Rails admin
  #mount RailsAdmin::Engine => 'admin', :as => 'rails_admin'

  match "attendances/import" => "attendances#import"
  resources :attendances
  resources :services
  resources :classrooms
  resources :parents
  resources :children

  root :to => "home#index"
  post "processCheckin" => "home#processCheckin"
  post "undoCheckin" => "home#undoCheckin"
end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id           :integer         not null, primary key
#  service_id   :integer
#  classroom_id :integer
#  child_id     :integer
#  created_at   :datetime
#  updated_at   :datetime
#
class Attendance < ActiveRecord::Base
  belongs_to :service
  belongs_to :classroom
  belongs_to :child

  validates_presence_of :service, :classroom, :child

  #
  # A query useful for counting attendances for each 
  # weekend. Brings back a list of objects for the date
  # range
  # {
  #   :service_date,
  #   :count
  # }
  def self.attendance_totals(start_date, end_date)
    select("date_trunc('day', services.service_date) as service_date, COUNT(service_id)").
    joins("RIGHT OUTER JOIN services ON attendances.service_id = services.id INNER JOIN children ON children.id = attendances.child_id").
    where('services.service_date' => start_date..end_date, 'children.inactive' => false).
    group("date_trunc('day', services.service_date)").
    order("date_trunc('day', services.service_date)")
  end
end
# == Schema Information
#
# Table name: attendances
#
#  id           :integer         not null, primary key
#  service_id   :integer
#  classroom_id :integer
#  child_id     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_filter :authenticate_volunteer!

  def import
    require 'dtcm_attendance_importer'

    unless params.empty? || params[:file].nil? || params[:class_id].nil?
      puts "Getting ready to parse"
      file = params[:file].tempfile

      DTCMAttendanceImporter.new(file, params[:class_id]).parse_file
    end

    @classrooms = Classroom.where("classrooms.name <> ?", "All").order(:id)
  end

  # GET /attendances
  # GET /attendances.xml
  def index
    @attendances = Attendance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attendances }
    end
  end

  # GET /attendances/1
  # GET /attendances/1.xml
  def show
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attendance }
    end
  end

  # GET /attendances/new
  # GET /attendances/new.xml
  def new
    @attendance = Attendance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attendance }
    end
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.xml
  def create
    @attendance = Attendance.new(params[:attendance])

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to(@attendance, :notice => 'Attendance was successfully created.') }
        format.xml  { render :xml => @attendance, :status => :created, :location => @attendance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attendance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attendances/1
  # PUT /attendances/1.xml
  def update
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      if @attendance.update_attributes(params[:attendance])
        format.html { redirect_to(@attendance, :notice => 'Attendance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attendance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.xml
  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to(attendances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.haml
= form_for @attendance do |f|
  -if @attendance.errors.any?
    #error_explanation
      %h2= "#{pluralize(@attendance.errors.count, "error")} prohibited this attendance from being saved:"
      %ul
        - @attendance.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/attendances/edit.html.haml
%h1 Editing attendance

= render 'form'

= link_to 'Show', @attendance
\|
= link_to 'Back', attendances_path

app/views/attendances/import.html.haml
= form_tag '/attendances/import', :multipart => true do
  = file_field_tag 'file'
  = select_tag :class_id, options_for_select(@classrooms.map { |c| [ c.name, c.id ] })
  = submit_tag('Import')

app/views/attendances/index.html.haml
%h1 Listing attendances

%table
  %tr
    %th
    %th
    %th

  - @attendances.each do |attendance|
    %tr
      %td= link_to 'Show', attendance
      %td= link_to 'Edit', edit_attendance_path(attendance)
      %td= link_to 'Destroy', attendance, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Attendance', new_attendance_path

app/views/attendances/new.html.haml
%h1 New attendance

= render 'form'

= link_to 'Back', attendances_path

app/views/attendances/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_attendance_path(@attendance)
\|
= link_to 'Back', attendances_path